### ISSUE TITLE
I had some problems compiling the new tonto-free version

### ISSUE THREAD

**Issue by MilitaoLucas** [peterspackman/crystalexplorer#20]
Hello, good morning. Trying the new version (I know this is very early, but this issue is relevant) I found some problems in unique_ptr in std::unique_ptr. I am not very familiar with C++ (working on getting better) but I found in StackOverflow that including the `<memory>` header seems to fix this problem. I was able to compile and run the new version this way. Other problem is that you didn't include OCC_PATH in the header file of settings.cpp. I was able to compile by providing:
```
const QString OCC_PATH = OCC_GROUP + "";
```
But I don't know what the default should actually be, so I didn't fell comfortable creating a PR.

**Comment by peterspackman** [comment]
Thanks for pointing this out - if you could mention which header file(s) were missing an include from the `<memory>` header that would be helpful!

The rework branch at the moment is 100% not ready for others to use (or probably even compile) and has many unresolved issues. I'm aiming to get an early release version ready within the next month.

**Comment by MilitaoLucas** [comment]
Oh, I totally forgot that. My bad. The new version had some problems, like looking for absolute paths, but I was able to work trough that. The results are looking similar to the older version, and I am liking it very much. Thank you for the awesome work! `kdtree.h` seems to be missing the `<memory>` header. Also, the OCC path is missing from `settings.h`.

**Comment by MilitaoLucas** [comment]
In the other topic, I was able to use HOZPIX in the main version fine. But I liked the new version better, and after working through the issues it seemed to work.

**Comment by MilitaoLucas** [comment]
Sure, I was just trying a little too much to make it work, so I could still include it in my undergrad thesis. Sorry for creating an issue for pre-alpha code.
