### ISSUE TITLE
Crystal Explorer appears broken under wayland

### ISSUE THREAD

**Issue by MilitaoLucas** [peterspackman/crystalexplorer#22]
Just a warning, that I found useful to put here. It works fine under xcb. So this is not in any way very important. But everytime I try to lunch it using QT_QPA_PLATFORM under wayland I get:
````
QEGLPlatformContext: Failed to create context: 3009
QRhiGles2: Failed to create temporary context
QEGLPlatformContext: Failed to create context: 3009
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
QEGLPlatformContext: Failed to create context: 3009
QOpenGLWidget: Failed to create context
````
I tried building using gcc and clang and I get the same errors.

**Comment by peterspackman** [comment]
At some point I'll check it out, but as you say it's low priority for now!

**Comment by MilitaoLucas** [comment]
I don't know when our exactly what you did, but it is working now. It always fun when you don't target something directly and fix it somehow. QT_QPA_PLATFORM=wayland ./CrystalExplorer doesn't crash anymore and I can plot surfaces just fine. I will close the issue as it seems to be solved.

**Comment by peterspackman** [comment]
Great to hear! Always nice when bugs fix themselves :)
